### ISSUE TITLE
No strict type checking for indexing with vars

### ISSUE THREAD

**Issue by ElijahAhianyo** [pynecone-io/reflex#1331]
This code shouldnt be allowed but it compiles into a js code that doesnt fail either:

```python
class State(rx.State):
    d: list[int] = [1, 2, 3]

    @rx.var
    def elements(self) -> dict[str, str]:
        return {"name": "reflex"}


def index():
    return rx.center(
        rx.text(State.elements[State.d]),
    )
```

**Comment by masenf** [comment]
Users are reporting regressions with this change https://discord.com/channels/1029853095527727165/1061874061250150441/1131440499501301814
